db:
  host: 'db'
  port: 3306,
  username: 'vilangspeak-user'
  password: 'GiLJko1Tf2GfJrJl'
  database: 'vilangspeak_db'

jwt:
  secret:
    access: 'zhibFHMZnv'
    refresh: 'znd1PxyVYq'
  exp_time:
    access: '5m'
    refresh: '30d'

root_account:
  name: 'Tuan Admin'
  username: 'admin-wU6J28Mjy4abBSVU'
  password: 'DlAMCFVbs8zl8MwD'
  birthday: '2001-01-02'