db:
  host: '127.0.0.1'
  port: 3306,
  username: 'vilangspeak-user'
  password: 'GiLJko1Tf2GfJrJl'
  database: 'vilangspeak_db'

jwt:
  secret:
    access: 'bKjFMNIA1e'
    refresh: 'DYpLWlvNdy'
  exp_time:
    access: '60s'
    refresh: '5m'

root_account:
  name: 'Tuan Admin'
  username: 'admin'
  password: '123456'
  birthday: '2001-01-01'